my_list = [7, 8, 9, 2, 3, 1, 4, 10, 5, 6]
my_second_list = my_list.copy()
print("Lista copiata este: ")
print(my_second_list)
my_second_list.sort()
print("Lista ordonata ascendent este: ")
print(my_second_list)
my_second_list.sort(reverse=True)
print("Lista ordonata descendent este: ")
print(my_second_list)
print("Numerele cu index par din lista sunt: ")
print(my_list[0:9:2])
print("Numerele cu index impar din lista sunt: ")
print(my_list[1:10:2])
print("Numerele multipli ai lui 3 sunt: ")
my_second_list.sort()
print(my_second_list[2:10:3])